[package]
name = "hamiziqbal/roblox-project"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
warp = "imezx/warp@1.0.14"
boattween = "boatbomber/boattween@1.0.1"
spr = "blackjackiee/spr@1.1.3"
janitor = "howmanysmall/janitor@1.17.0"