return {
    ["Forest"] = {
        Name = "Forest",
        Icon = "rbxassetid://11612788415",
        Levels = {
            Easy = 0,
            Medium = 5,
            Hard = 10,
        }
    },
    ["Desert"] = {
        Name = "Desert",
        Icon = "rbxassetid://16949750485",
        Levels = {
            Easy = 15,
            Medium = 20,
            Hard = 25,
        }
    },
    ["Volcano"] = {
        Name = "Volcano",
        Icon = "rbxassetid://6991942303",
        Levels = {
            Easy = 30,
            Medium = 40,
            Hard = 50,
        }
    },
}