local rarities = {
    ["Common"] = {
        BackgroundColor = Color3.fromRGB(255,255,255),
        BorderColor = Color3.fromRGB(108, 108, 108),
    },
    ["Uncommon"] = {
        BackgroundColor = Color3.fromRGB(115, 209, 111),
        BorderColor = Color3.fromRGB(78, 150, 78),
    },
    ["Rare"] = {
        BackgroundColor = Color3.fromRGB(140, 186, 255),
        BorderColor = Color3.fromRGB(81, 110, 148),
    },
}

return rarities